{
 "title": "Analise Energia Eléctrica - Flávio",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "CustoEletricidadeDia", "query": "0.248091,0.198522" },
   { "name": "CustoEletricidadeNoite", "query": "0.115497,0.198522" }
  ]
 },
 "panels": [
  {
   "title": "Total EDP",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Messungen",
     "select": [
      [
       { "params": [ "activePower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Solar",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Messungen",
     "select": [
      [
       { "params": [ "activePower2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Aproveitamento Solar",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Messungen",
     "query": "SELECT ((SUM(\"Solar\") - SUM(\"ExportEDP\")) * 100) / SUM(\"Solar\") AS \"Poupança Solar\", time FROM (SELECT (mean(\"activePower2\") / 1000)  AS \"Solar\",  abs(mean((\"activeGridExport\")) / 1000)  AS \"ExportEDP\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h))",
     "select": [
      [
       { "params": [ "activePower3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumo Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 0 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Messungen",
     "query": "SELECT last(\"activePower3\") FROM \"Messungen\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "activePower3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gasto Hoje",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "format": "currencyEUR",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Messungen",
     "query": "SELECT SUM(\"Dia\") + SUM(Noite) AS \"Custo EDP\", time  FROM (SELECT (mean(\"activeGridImportCostDia\") / 1000) * $CustoEletricidadeDia  AS \"Dia\", (mean(\"activeGridImportCostNoite\") / 1000)*$CustoEletricidadeNoite AS \"Noite\"  FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h))",
     "select": [
      [
       { "params": [ "activePower3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Poupança Solar",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "currencyEUR",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Messungen",
     "query": "SELECT SUM(\"Solar\") + SUM(\"ExportEDP\") AS \"Poupança Solar\", time FROM (SELECT (mean(\"activePower2\") / 1000) * $CustoEletricidadeDia AS \"Solar\",  (mean(\"activeGridExport\") / 1000) * $CustoEletricidadeDia AS \"ExportEDP\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h))",
     "select": [
      [
       { "params": [ "activePower3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "AMP Rede",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Messungen",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Amp Solar",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Messungen",
     "select": [
      [
       { "params": [ "current2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gasto semana",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "format": "currencyEUR",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Messungen",
     "query": "SELECT SUM(\"Dia\") + SUM(Noite) AS \"Custo EDP\", time  FROM (SELECT (mean(\"activeGridImportCostDia\") / 1000) * $CustoEletricidadeDia  AS \"Dia\", (mean(\"activeGridImportCostNoite\") / 1000)*$CustoEletricidadeNoite AS \"Noite\"  FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h))",
     "select": [
      [
       { "params": [ "activePower3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gasto mês",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "currencyEUR",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Messungen",
     "query": "SELECT SUM(\"Dia\") + SUM(Noite) AS \"Custo EDP\", time  FROM (SELECT (mean(\"activeGridImportCostDia\") / 1000) * $CustoEletricidadeDia  AS \"Dia\", (mean(\"activeGridImportCostNoite\") / 1000)*$CustoEletricidadeNoite AS \"Noite\"  FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h))",
     "select": [
      [
       { "params": [ "activePower3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Poupança Solar semana",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "currencyEUR",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Messungen",
     "query": "SELECT SUM(\"Solar\") + SUM(\"ExportEDP\") AS \"Poupança Solar\", time FROM (SELECT (mean(\"activePower2\") / 1000) * $CustoEletricidadeDia AS \"Solar\",  (mean(\"activeGridExport\") / 1000) * $CustoEletricidadeDia AS \"ExportEDP\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(31d) ",
     "select": [
      [
       { "params": [ "activePower3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Poupança Solar mês",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "currencyEUR",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Messungen",
     "query": "SELECT SUM(\"Solar\") + SUM(\"ExportEDP\") AS \"Poupança Solar\", time FROM (SELECT (mean(\"activePower2\") / 1000) * $CustoEletricidadeDia AS \"Solar\",  (mean(\"activeGridExport\") / 1000) * $CustoEletricidadeDia AS \"ExportEDP\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(31d) ",
     "select": [
      [
       { "params": [ "activePower3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Analise Energia",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Consumo Rede",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "select": [
      [
       { "params": [ "activeGridImport" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Produção solar",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "select": [
      [
       { "params": [ "activePower2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Envio Rede",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "query": "SELECT ABS(last(\"activeGridExport\")) FROM \"Messungen\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "activeGridExport" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Consumo Total",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "select": [
      [
       { "params": [ "activePower3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Corrente Eletrica",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "AMP Rede",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "query": "SELECT last(\"current\") FROM \"Messungen\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "AMP Solar",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "select": [
      [
       { "params": [ "current2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumo do Dia",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Consumo Rede",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"activeGridImport\")  / 1000 AS \"Rede Import\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Produção Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"activePower2\")  / 1000 AS \"Energia Solar\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Envio Rede",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"activeGridExport\") / 1000 AS \"Rede Export\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltagem",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Spannung",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumo Total / Hora",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 23 },
   "targets": [
    {
     "alias": "Consumo Total",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "query": "SELECT mean(\"activePower3\")  / 1000 AS \"Consumo Total\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "activePower3" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Energie",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "query": "SELECT mean(\"activeGridImport\")  / 1000 AS \"Consumo Rede\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "activePower3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Energie",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "query": "SELECT mean(\"activePower2\")  / 1000 AS \"Produção Solar\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "activePower3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Energie",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "query": "SELECT abs(mean(\"activeGridExport\")) / 1000 AS \"Envio Rede\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "activePower3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Potência Elétrica",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    {
     "alias": "Rede",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "select": [
      [
       { "params": [ "apparentPower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "select": [
      [
       { "params": [ "apparentPower2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Custo por dia",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 31 },
   "targets": [
    {
     "alias": "Energie",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "query": "SELECT SUM(\"Dia\") AS \"Custo Dia\", time  FROM (SELECT (mean(\"activeGridImportCostDia\") / 1000) *$CustoEletricidadeDia AS \"Dia\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "activeGridImportCostDia" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100*0.2017" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Energie",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "query": "SELECT SUM(\"Noite\") AS \"Custo Noite\", time  FROM (SELECT (mean(\"activeGridImportCostNoite\") / 1000)* $CustoEletricidadeNoite AS \"Noite\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "activeGridImportCostNoite" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100*0.0939" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Energie",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "query": "SELECT SUM(\"Noite\") + SUM(\"Dia\") AS \"Simples\", time  FROM (SELECT (mean(\"activeGridImportCostNoite\") / 1000)* 0.198522 AS \"Noite\",  (mean(\"activeGridImportCostDia\") / 1000)* 0.198522 AS \"Dia\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "activeGridImportCostNoite" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100*0.0939" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Energie",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "query": "SELECT SUM(\"Noite\") + SUM(\"Dia\") AS \"Bi-Horario\", time  FROM (SELECT (mean(\"activeGridImportCostNoite\") / 1000)* $CustoEletricidadeNoite AS \"Noite\",  (mean(\"activeGridImportCostDia\") / 1000)* $CustoEletricidadeDia AS \"Dia\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "activeGridImportCostNoite" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100*0.0939" ], "type": "math" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"Solar\") + SUM(\"ExportEDP\") AS \"Poupança Solar\", time FROM (SELECT (mean(\"activePower2\") / 1000) * $CustoEletricidadeDia AS \"Solar\",  (mean(\"activeGridExport\") / 1000) * $CustoEletricidadeDia AS \"ExportEDP\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"Solar\") AS \"Produção Solar\", time, SUM(\"ExportEDP\") AS \"Entrega EDP\" FROM (SELECT (mean(\"activePower2\") / 1000) * $CustoEletricidadeDia AS \"Solar\",  (mean(\"activeGridExport\") / 1000) * $CustoEletricidadeDia AS \"ExportEDP\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumo do ultimo mês",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Dia",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "query": "SELECT SUM(\"Dia\") AS \"Dia\", time  FROM (SELECT (mean(\"activeGridImportCostDia\") / 1000) AS \"Dia\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "activePower3" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Noite",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"Noite\") AS \"Noite\", time  FROM (SELECT (mean(\"activeGridImportCostNoite\") / 1000)  AS \"Noite\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Consumo Solar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"Solar\") + SUM(\"ExportEDP\") AS \"Consumo Solar\", time FROM (SELECT (mean(\"activePower2\") / 1000)  AS \"Solar\",  (mean(\"activeGridExport\") / 1000) AS \"ExportEDP\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"Solar\") AS \"Produção Solar\", time, SUM(\"ExportEDP\") AS \"Entrega EDP\" FROM (SELECT (mean(\"activePower2\") / 1000) AS \"Solar\",  (mean(\"activeGridExport\") / 1000)  AS \"ExportEDP\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "kWh Por dia",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 39 },
   "targets": [
    {
     "alias": "Energie",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "query": "SELECT SUM(\"Dia\") AS \"Dia\", time  FROM (SELECT (mean(\"activeGridImportCostDia\") / 1000) AS \"Dia\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "activeGridImportCostDia" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100*0.2017" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Energie",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "query": "SELECT SUM(\"Noite\") AS \"Noite\", time  FROM (SELECT (mean(\"activeGridImportCostNoite\") / 1000)  AS \"Noite\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "activeGridImportCostNoite" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100*0.0939" ], "type": "math" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"Solar\") + SUM(\"ExportEDP\") AS \"Consumo Solar\", time FROM (SELECT (mean(\"activePower2\") / 1000)  AS \"Solar\",  (mean(\"activeGridExport\") / 1000) AS \"ExportEDP\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"Solar\") AS \"Produção Solar\", time, SUM(\"ExportEDP\") AS \"Entrega EDP\" FROM (SELECT (mean(\"activePower2\") / 1000) AS \"Solar\",  (mean(\"activeGridExport\") / 1000)  AS \"ExportEDP\" FROM \"Messungen\" WHERE $timeFilter GROUP BY time(1h)) GROUP BY time(1d) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Potência Reativa",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "voltampreact" }
   ],
   "targets": [
    {
     "alias": "Rede",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "select": [
      [
       { "params": [ "reactivePower" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Messungen",
     "select": [
      [
       { "params": [ "reactivePower2" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}